"""changeling Phase 0 gate runs — AUTOGENERATED by scripts/build_kernel.py; do not edit by hand. See SPEC.md / PREREG_P0.md in the repo."""

# ===== changeling/__init__.py =====
"""changeling — breeding transferable in-context learners. See SPEC.md."""

OBS_DIM = 64
N_ACT = 8
IN_DIM = OBS_DIM + N_ACT + 2  # obs, onehot(last action), last reward, boundary bit

# ===== changeling/envs.py =====
"""Phase 0 environments in pure JAX.

An env is a dict of pure functions sharing the fixed interface protocol
(SPEC section 2): obs padded to OBS_DIM, actions in [0, N_ACT).

  sample_task(key) -> task            (per-lifetime parameters)
  reset(key, task) -> (state, obs)    (per-episode)
  step(state, a, key, task) -> (state, obs, reward, done, metric)

`metric` is the env's gate statistic (bandit: pulled best arm; catch: success,
nonzero only on terminal steps). T is lifetime length in steps.
"""
import jax
import jax.numpy as jnp



def bandit_env(n_arms=8, lifetime=200, needle=False, mix=0.0):
    """Bernoulli bandit. Default: p_i ~ U(0,1) per lifetime (forgiving —
    second-best is typically close to best, so satisficing nearly pays).
    needle=True: one arm at 0.9, the rest at 0.1 — finding the needle is
    constitutive of success; settling pays 0.1. mix=p: each lifetime is a
    needle task w.p. p, else uniform (curriculum contrast). One-step episodes."""
    assert 2 <= n_arms <= 8

    def sample_task(key):
        if needle:
            pos = jax.random.randint(key, (), 0, n_arms)
            return jnp.where(jnp.arange(n_arms) == pos, 0.9, 0.1)
        return jax.random.uniform(key, (n_arms,))

    if mix > 0:
        base = sample_task

        def sample_task(key):  # noqa: F811 — mixture wraps the base sampler
            ku, kn, kc = jax.random.split(key, 3)
            pos = jax.random.randint(kn, (), 0, n_arms)
            needle_p = jnp.where(jnp.arange(n_arms) == pos, 0.9, 0.1)
            return jnp.where(jax.random.bernoulli(kc, mix),
                             needle_p, base(ku))

    def reset(key, task):
        return (), jnp.zeros(OBS_DIM)

    def step(state, a, key, task):
        valid = a < n_arms                      # SPEC §2: surplus actions = no-op
        a_eff = jnp.where(valid, a, 0)          # safe gather index when invalid
        pull = jax.random.bernoulli(key, task[a_eff]).astype(jnp.float32)
        r = jnp.where(valid, pull, 0.0)         # a no-op earns nothing
        best = (a_eff == jnp.argmax(task)).astype(jnp.float32)
        metric = jnp.where(valid, best, 0.0)    # and never counts as best-arm
        return (), jnp.zeros(OBS_DIM), r, jnp.bool_(True), metric

    return dict(sample_task=sample_task, reset=reset, step=step,
                T=lifetime, name=f"bandit{n_arms}")


def catch_env(episodes=32):
    """bsuite-style Catch: 10x5 board, ball falls one row/step, paddle on the
    bottom row. +1 catch / -1 miss on the terminal step. 9-step episodes."""
    ROWS, COLS = 10, 5

    def _obs(state):
        ball_row, ball_col, paddle = state
        grid = jnp.zeros((ROWS, COLS))
        grid = grid.at[ball_row, ball_col].set(1.0)
        grid = grid.at[ROWS - 1, paddle].set(1.0)
        flat = grid.reshape(-1)
        return jnp.concatenate([flat, jnp.zeros(OBS_DIM - flat.shape[0])])

    def sample_task(key):
        return jnp.zeros(())  # no task variation in P0

    def reset(key, task):
        col = jax.random.randint(key, (), 0, COLS)
        state = (jnp.int32(0), col, jnp.int32(COLS // 2))
        return state, _obs(state)

    def step(state, a, key, task):
        ball_row, ball_col, paddle = state
        move = jnp.where(a == 0, -1, jnp.where(a == 2, 1, 0))  # 3..7 -> stay
        paddle = jnp.clip(paddle + move, 0, COLS - 1)
        ball_row = ball_row + 1
        done = ball_row >= ROWS - 1
        caught = (ball_col == paddle).astype(jnp.float32)
        r = jnp.where(done, 2.0 * caught - 1.0, 0.0)
        state = (ball_row, ball_col, paddle)
        return state, _obs(state), r, done, jnp.where(done, caught, 0.0)

    return dict(sample_task=sample_task, reset=reset, step=step,
                T=episodes * (ROWS - 1), name="catch")


def cbandit_env(n_arms=8, lifetime=256, C_ctx=5, frozen_rule=True, rule_seed=0,
                mix=0.0, hi_std=0.8, lo_std=0.2, hi_needle=0.95, lo_needle=0.05):
    """Contextual bandit (PREREG_P1 §1, the PRIMARY env). Each one-step trial
    draws a context c ~ U{0..C-1}; obs = onehot(c) padded to OBS_DIM. The correct
    arm is an injective map y(c): C->K (C_ctx<=n_arms). Pulling y(c) pays `hi`,
    else `lo`; the curriculum mixes a sharp "needle" margin (0.95/0.05) w.p. `mix`
    else standard (0.8/0.2). metric = pulled-correct-arm (the gate statistic).

    Two modes (PREREG_P1 B3):
      frozen_rule=True  (cbandit-FR, HEADLINE) — y is FIXED, seeded once from
        `rule_seed`, SHARED across every lifetime and eval. The only per-lifetime
        unknown is the interface (P,π) applied in rollout: the within-lifetime
        slope is pure interface-inference speed.
      frozen_rule=False (cbandit-FG, co-gated) — y resampled per lifetime ⇒
        genuine in-context task-learning under randomization.

    The env is interface-AGNOSTIC: obs-projection P and action-permutation π are
    applied by rollout/collect (B2). step() scores whatever arm it receives, so
    the metric is computed on the post-permutation arm (what was actually pulled).
    """
    assert 2 <= n_arms <= N_ACT
    assert 2 <= C_ctx <= n_arms          # injective map needs C <= K
    assert C_ctx <= OBS_DIM

    def _rule(key):
        # injective C->K: first C entries of a random arm permutation
        return jax.random.permutation(key, n_arms)[:C_ctx]

    Y_FIXED = _rule(jax.random.PRNGKey(rule_seed))   # FR closure constant

    def sample_task(key):
        ky, kn = jax.random.split(key)
        y = Y_FIXED if frozen_rule else _rule(ky)
        needle = jax.random.bernoulli(kn, mix)
        hi = jnp.where(needle, hi_needle, hi_std)
        lo = jnp.where(needle, lo_needle, lo_std)
        return dict(y=y, hi=hi, lo=lo)

    def reset(key, task):
        c = jax.random.randint(key, (), 0, C_ctx)
        obs = jnp.zeros(OBS_DIM).at[c].set(1.0)
        return c, obs

    def step(state, a, key, task):
        c = state
        valid = a < n_arms                       # SPEC §2: surplus actions = no-op
        a_eff = jnp.where(valid, a, 0)
        is_correct = jnp.logical_and(valid, a_eff == task["y"][c])
        p = jnp.where(is_correct, task["hi"], task["lo"])
        r = jnp.where(valid, jax.random.bernoulli(key, p).astype(jnp.float32), 0.0)
        metric = is_correct.astype(jnp.float32)
        # one-step episode (done every trial); rollout auto-resets a new context
        return c, jnp.zeros(OBS_DIM), r, jnp.bool_(True), metric

    return dict(sample_task=sample_task, reset=reset, step=step,
                T=lifetime, name=f"cbandit{'FR' if frozen_rule else 'FG'}")


ENVS = {"bandit": bandit_env, "catch": catch_env, "cbandit": cbandit_env}

# ===== changeling/agent.py =====
"""S1 substrate: plain GRU, pure JAX. Params are a flat dict pytree."""
import jax
import jax.numpy as jnp



def init_gru(key, hidden=128, in_dim=IN_DIM, out_dim=N_ACT):
    ks = jax.random.split(key, 7)
    s_in, s_h = 1.0 / jnp.sqrt(in_dim), 1.0 / jnp.sqrt(hidden)

    def mat(k, shape, scale):
        return jax.random.normal(k, shape) * scale

    return {
        "Wxz": mat(ks[0], (in_dim, hidden), s_in), "Whz": mat(ks[1], (hidden, hidden), s_h),
        "bz": jnp.zeros(hidden),
        "Wxr": mat(ks[2], (in_dim, hidden), s_in), "Whr": mat(ks[3], (hidden, hidden), s_h),
        "br": jnp.zeros(hidden),
        "Wxh": mat(ks[4], (in_dim, hidden), s_in), "Whh": mat(ks[5], (hidden, hidden), s_h),
        "bh": jnp.zeros(hidden),
        "Wo": mat(ks[6], (hidden, out_dim), s_h), "bo": jnp.zeros(out_dim),
    }


def gru_step(p, h, x):
    z = jax.nn.sigmoid(x @ p["Wxz"] + h @ p["Whz"] + p["bz"])
    r = jax.nn.sigmoid(x @ p["Wxr"] + h @ p["Whr"] + p["br"])
    hh = jnp.tanh(x @ p["Wxh"] + (r * h) @ p["Whh"] + p["bh"])
    h = (1.0 - z) * h + z * hh
    return h, h @ p["Wo"] + p["bo"]


def hidden_size(params):
    return params["bz"].shape[0]

# ===== changeling/looped.py =====
"""Increment A (SPEC §5b/S3-M.1): the looped core + adaptive-K micro-turns,
PonderNet-MARGINALIZED. Standalone + pure — no store, no slow bank yet.

The per-env-step computation runs K_max weight-tied micro-turns of the core over
the SAME step input x (hourglass: recurrent DEPTH over fixed context), and COMMITS
THE MARGINAL MIXTURE pi = sum_k p_k * softmax(logits_k) — never a discrete halt
sample. Marginalization is the over-determined lynchpin (PPO replay-exactness +
antithetic-CRN + teacher-forcing all force it): `micro_loop` is a deterministic
pure function of (params, h, x), so collect() and loss_fn.forward() will produce
bitwise-identical commit log-probs.

REDUCTION INVARIANT (the regression spine): at K_max=1 this collapses exactly to
`gru_step` -> log_softmax — so the whole substrate is a strict superset of today's
harness. Verified in __main__.

`make_step(cfg)` is the B1 abstract step_fn: it returns a pure
    step(params, h, x) -> (h_new, sample_score, logp_all, value, aux)
that the rollout / collect / loss_fn forward all share. cfg["loop"]=False emits the
EXACT legacy gru path (sample_score = RAW logits, so categorical draws are bitwise
identical to the pre-refactor harness — the G0-A 0.6216 regression spine); loop=True
emits the marginalized micro-loop (sample_score = logp_all = commit_logp).
"""
import jax
import jax.numpy as jnp



def init_looped(key, hidden=128):
    """GRU core (policy logits via Wo/bo) + a halting head + a value head.

    Halt head is named Whalt/bhalt (NOT bh) — the GRU already owns p["bh"] as its
    candidate-state bias; colliding on that key silently ties two unrelated params.
    """
    kg, kh, kv = jax.random.split(key, 3)
    p = init_gru(kg, hidden=hidden)  # carries Wxz..Wo/bo (incl. candidate bias bh)
    s_h = 1.0 / jnp.sqrt(hidden)
    p["Whalt"] = jax.random.normal(kh, (hidden, 1)) * s_h
    p["bhalt"] = jnp.zeros(1)
    p["Wv"] = jax.random.normal(kv, (hidden, 1)) * s_h
    p["bv"] = jnp.zeros(1)
    return p


def _ponder_p(halt_k, k_max, k_min):
    """PonderNet halting masses p_k over k=1..K_max (cumulative-product), with a
    K_min floor (no halt before k_min) and forced halt at K_max (residual mass)."""
    lam = jax.nn.sigmoid(halt_k)                       # (K,)
    lam = lam * (jnp.arange(k_max) >= (k_min - 1))     # K_min>=2 floor
    lam = lam.at[-1].set(1.0)                          # must halt by K_max -> sum p = 1
    notbefore = jnp.concatenate(                       # prod_{j<k}(1 - lam_j)
        [jnp.ones(1), jnp.cumprod(1.0 - lam)[:-1]])
    return lam * notbefore                             # (K,)


def geometric_prior(lam_p, k_max, k_min):
    """Truncated geometric prior over k=1..K_max (PonderNet KL target), zeroed
    below k_min and renormalized over the realizable support."""
    k = jnp.arange(k_max)                              # 0..K_max-1 -> k=1..K_max
    g = lam_p * (1.0 - lam_p) ** k
    g = g * (k >= (k_min - 1))                         # match the K_min floor
    return g / g.sum()


def kl_to_geometric(p, lam_p, k_max, k_min):
    """KL(p || geometric_prior). p_k=0 terms contribute 0 (PonderNet L_reg)."""
    g = geometric_prior(lam_p, k_max, k_min)
    return jnp.where(p > 0, p * (jnp.log(p + 1e-12) - jnp.log(g + 1e-12)), 0.0).sum()


def micro_loop(p, h, x, k_max=8, k_min=2):
    """One env-step's internal compute. Returns (h_new, commit_logp, commit_v, aux).
    Pure in (p, h, x): no RNG, no state outside the args -> replay-exact."""
    def turn(m, _):
        m, logits = gru_step(p, m, x)                  # weight-tied core re-reads x
        halt = (m @ p["Whalt"] + p["bhalt"])[0]
        v = (m @ p["Wv"] + p["bv"])[0]
        return m, (m, logits, halt, v)

    _, (ms, logits_k, halt_k, v_k) = jax.lax.scan(turn, h, None, length=k_max)
    # ms (K,H)  logits_k (K,A)  halt_k (K,)  v_k (K,)
    pk = _ponder_p(halt_k, k_max, k_min)               # (K,)
    probs_k = jax.nn.softmax(logits_k, axis=-1)        # (K,A)
    pi = (pk[:, None] * probs_k).sum(0)                # (A,) marginal commit dist
    commit_logp = jnp.log(pi + 1e-12)
    commit_v = (pk * v_k).sum()
    h_new = (pk[:, None] * ms).sum(0)                  # marginal committed state
    e_k = (pk * (jnp.arange(k_max) + 1.0)).sum()       # E[K]
    aux = dict(E_K=e_k, p=pk, logits_k=logits_k, v_k=v_k, halt_k=halt_k)
    return h_new, commit_logp, commit_v, aux


def make_step(cfg):
    """B1 abstract step_fn. Returns a pure
        step(params, h, x) -> (h_new, sample_score, logp_all, value, aux)
    where `sample_score` is what jax.random.categorical consumes, `logp_all` is the
    (A,) action log-prob vector (for stored logp / entropy / the PPO ratio), `value`
    is the committed state-value (commit_v) for the looped path or None for legacy
    (PPO computes the legacy value from its own top-level head), and `aux` always
    carries E_K.

    loop=False is byte-identical to the legacy harness: sample_score = RAW gru
    logits, so categorical(key, sample_score) draws the same action bit-for-bit."""
    if not cfg.get("loop", False):
        def step(params, h, x):
            h2, logits = gru_step(params, h, x)
            return h2, logits, jax.nn.log_softmax(logits), None, {
                "E_K": jnp.float32(1.0)}
        return step

    k_max = int(cfg["k_max"])
    k_min = int(cfg.get("k_min", 2))

    def step(params, h, x):
        h2, clp, cv, aux = micro_loop(params, h, x, k_max=k_max, k_min=k_min)
        return h2, clp, clp, cv, aux
    return step


# ----------------------------------------------------------------------------

# ===== changeling/interface.py =====
"""B2 (PREREG_P1 §1 "Randomization family"): per-lifetime interface randomization.

Each lifetime is handed a FIXED, INVERTIBLE interface (P, perm), resampled every
lifetime, and the agent must re-infer it in-context. The interface is applied by
rollout/collect — this module only SAMPLES it (pure, keyed):

  P    — orthogonal obs projection (OBS_DIM x OBS_DIM), applied as P @ obs.
         expm-orthogonal (train family): P(alpha)=expm(alpha·A), A skew-symmetric
         ⇒ orthogonal for all alpha, EXACTLY I at alpha=0 (reproduces P0), norm-
         preserving (no reward-magnitude leak), kappa=1 always. `PROJ_C` is
         calibrated (calibrate_c) so the mean self-correlation diag(P)≈0 at alpha=1.
         signed-perm (held-out T-family, eval-only): P = D·Pi (Pi permutation,
         D=diag(±1)) — structurally disjoint from the dense-rotation train family,
         proves general interface-inference (G1-G). alpha=0 ⇒ I.
  perm — action permutation in S_{N_ACT}: identity w.p.(1−alpha) else uniform.
         Agent slot a -> env slot perm[a]; alpha=0 ⇒ identity (no-op).

alpha=0 ⇒ (I, identity): a mathematical no-op, so an alpha=0 lifetime is identical
to the un-randomized P0 protocol. Single-axis arms (G1-C/D, C7-P/π) come from
alpha_obs / alpha_act overrides (set the other axis to 0).
"""
import jax
import jax.numpy as jnp
from jax.scipy.linalg import expm


# Calibrated 2026-06-13 (calibrate_c, n=64, batch=512): c≈1.94 drives the expected
# mean self-correlation E[mean_i P[i,i]] to ≈0 at alpha=1 (fully decorrelated
# projection). Re-run calibrate_c if OBS_DIM changes. This is the §4 projection-c
# smoke result (un-metered).
PROJ_C = 1.94


def _skew(key, n, c):
    """Skew-symmetric generator A = c·(G−Gᵀ)/√(2n) (PREREG_P1 §1)."""
    g = jax.random.normal(key, (n, n))
    return c * (g - g.T) / jnp.sqrt(2.0 * n)


def sample_obs_proj(key, alpha, n=OBS_DIM, proj_family="expm-orthogonal", c=PROJ_C):
    """Orthogonal obs projection P (n x n). alpha=0 ⇒ I for both families."""
    if proj_family == "expm-orthogonal":
        return expm(alpha * _skew(key, n, c))
    if proj_family == "signed-perm":
        kp, ks = jax.random.split(key)
        perm = jax.random.permutation(kp, n)
        signs = jnp.where(jax.random.bernoulli(ks, 0.5, (n,)), 1.0, -1.0)
        pi = jnp.eye(n)[perm]                      # permutation matrix
        p_full = signs[:, None] * pi               # D·Pi (rows signed)
        # discrete family: used at eval alpha=1; alpha=0 ⇒ exact identity
        return jnp.where(alpha > 0, p_full, jnp.eye(n))
    raise ValueError(f"unknown proj_family {proj_family!r}")


def sample_act_perm(key, alpha, n=N_ACT):
    """Action permutation. identity w.p.(1−alpha) else uniform ∈ S_n. alpha=0 ⇒ id."""
    ku, kb = jax.random.split(key)
    perm = jax.random.permutation(ku, n)
    use = jax.random.bernoulli(kb, alpha)
    return jnp.where(use, perm, jnp.arange(n))


def sample_interface(key, alpha, proj_family="expm-orthogonal", n_obs=OBS_DIM,
                     n_act=N_ACT, c=PROJ_C, alpha_obs=None, alpha_act=None):
    """Per-lifetime interface (P, perm). Pure in key. alpha_obs/alpha_act override
    the shared alpha to isolate a single axis (e.g. alpha_act=0 ⇒ P-only)."""
    a_obs = alpha if alpha_obs is None else alpha_obs
    a_act = alpha if alpha_act is None else alpha_act
    kp, ka = jax.random.split(key)
    P = sample_obs_proj(kp, a_obs, n_obs, proj_family, c)
    perm = sample_act_perm(ka, a_act, n_act)
    return P, perm


def identity_interface(n_obs=OBS_DIM, n_act=N_ACT):
    """The explicit no-op interface (P=I, perm=identity)."""
    return jnp.eye(n_obs), jnp.arange(n_act)


# Disjoint fold for interface keys: keeps interface sampling OFF the existing
# task/rollout split streams, so alpha=None runs reproduce the pre-B2 harness
# bit-for-bit, and eval interfaces stay disjoint from training.
IFACE_FOLD = 0x1FACE


def make_iface_fn(config, for_eval=False):
    """Build a per-lifetime interface sampler iface_fn(key) -> (P, perm) from a
    run config, or None when interface randomization is off (config['alpha'] is
    None) — in which case the whole harness takes the byte-identical no-iface path.
    For eval, `proj_family` may be overridden by `eval_proj_family` (the held-out
    T-family, G1-G). Single-axis arms via `alpha_obs`/`alpha_act`."""
    import functools
    alpha = config.get("alpha")
    if alpha is None:
        return None
    fam = config.get("proj_family", "expm-orthogonal")
    if for_eval:
        fam = config.get("eval_proj_family", fam)
    return functools.partial(
        sample_interface, alpha=float(alpha), proj_family=fam,
        c=float(config.get("projection_c", PROJ_C)),
        alpha_obs=config.get("alpha_obs"), alpha_act=config.get("alpha_act"))


def calibrate_c(key, n=OBS_DIM, batch=512, lo=0.1, hi=12.0, iters=40):
    """Bisection on c so the expected mean self-correlation E[mean_i P[i,i]] ≈ 0 at
    alpha=1 (decorrelated projection). diag(P)=corr(P·eᵢ,eᵢ) since P orthogonal.
    Monotone-decreasing in c over the useful range. Returns the calibrated c."""
    keys = jax.random.split(key, batch)

    def mean_diag(c):
        Ps = jax.vmap(lambda k: expm(_skew(k, n, c)))(keys)
        return jnp.mean(jax.vmap(jnp.diag)(Ps))     # E[mean_i P[i,i]]

    lo, hi = jnp.float32(lo), jnp.float32(hi)
    for _ in range(iters):
        mid = 0.5 * (lo + hi)
        lo, hi = jax.lax.cond(mean_diag(mid) > 0.0,
                              lambda: (mid, hi), lambda: (lo, mid))
    return float(0.5 * (lo + hi))


# ----------------------------------------------------------------------------

# ===== changeling/rollout.py =====
"""One lifetime: RL^2 protocol. Memory persists across episodes within a
lifetime; env auto-resets on done (same task). Controls (PREREG_P0):
  c4 — blind the agent's reward *input* with a fair coin (env reward still
       scored); in-context learning should collapse where reward is the only cue.
  c5 — reset hidden state on every episode boundary; memory is the only
       learning mechanism, so this is the no-memory control. NOTE: the RL²
       input channel (last action/reward) still flows — C5 bounds the
       non-recurrent component, not memory absolutely.
  c6 — full amnesia: C5 plus zeroed last-action/last-reward inputs; nothing
       carries across steps through the RL² channels. On memory-dependent envs
       (bandit: obs is constant) performance is chance-level; on envs solvable
       from the current observation (catch: obs carries the board) C6 stays near
       main — it ablates the RL² channels, not the agent's reactivity.
"""
import jax
import jax.numpy as jnp


# Default substrate = the legacy gru step. make_step({}) returns sample_score =
# RAW logits, so categorical(key, sample_score) draws the same action bit-for-bit
# as the pre-B1 harness — rollout(step=None) is byte-identical to the old code.
_LEGACY_STEP = make_step({})


def rollout(env, params, task, key, c4=False, c5=False, c6=False, step=None,
            iface=None):
    """Returns (rewards, metrics, dones, e_ks) arrays of shape (T,). `e_ks` is the
    per-step E[K] micro-turn count (all-ones on the legacy/loop=False substrate);
    it is the K-collapse observable and feeds the ES ponder cost. `step` is a B1
    step_fn from looped.make_step; None -> the legacy gru path.

    `iface` (B2) is a per-lifetime interface (P, perm) held FIXED across the
    lifetime: the obs is projected `P @ obs` before the agent sees it, and the
    agent's raw slot `a` reaches the env as `perm[a]` (the agent still remembers
    its RAW action via the RL² channel). iface=None ⇒ no projection/permutation,
    byte-identical to the pre-B2 harness; an identity interface (P=I, perm=id) is
    a mathematical no-op."""
    if step is None:
        step = _LEGACY_STEP
    if iface is not None:
        P, perm = iface
    if c6:
        c5 = True
    T = env["T"]
    key, k0 = jax.random.split(key)
    state0, obs0 = env["reset"](k0, task)
    h0 = jnp.zeros(hidden_size(params))
    carry0 = (h0, state0, obs0, jnp.zeros(N_ACT), jnp.float32(0.0),
              jnp.float32(1.0), key)

    def step_fn(carry, _):
        h, state, obs, last_a, last_r, boundary, key = carry
        key, ka, kr, kres, kc4 = jax.random.split(key, 5)
        r_in = jax.random.bernoulli(kc4, 0.5).astype(jnp.float32) if c4 else last_r
        if c6:
            last_a, r_in = jnp.zeros_like(last_a), jnp.float32(0.0)
        obs_in = P @ obs if iface is not None else obs
        x = jnp.concatenate([obs_in, last_a, jnp.array([r_in, boundary])])
        h, sample_score, _logp_all, _v, aux = step(params, h, x)
        a = jax.random.categorical(ka, sample_score)
        a_env = perm[a] if iface is not None else a
        state, obs, r, done, metric = env["step"](state, a_env, kr, task)
        # auto-reset on episode end, same task
        rs_state, rs_obs = env["reset"](kres, task)
        state = jax.tree_util.tree_map(
            lambda new, old: jnp.where(done, new, old), rs_state, state)
        obs = jnp.where(done, rs_obs, obs)
        if c5:
            h = h * (1.0 - done.astype(jnp.float32))
        carry = (h, state, obs, jax.nn.one_hot(a, N_ACT), r,
                 done.astype(jnp.float32), key)
        return carry, (r, metric, done.astype(jnp.float32), aux["E_K"])

    _, (rewards, metrics, dones, e_ks) = jax.lax.scan(
        step_fn, carry0, None, length=T)
    return rewards, metrics, dones, e_ks


def late_weighted_fitness(rewards):
    """Fitness weights ramp 0.5 -> 1.5 across the lifetime (selects for
    improvement, not just performance). PREREG_P0 locked."""
    T = rewards.shape[0]
    w = jnp.linspace(0.5, 1.5, T)
    return jnp.sum(w * rewards) / jnp.sum(w)


def q4_fitness(rewards):
    """Final-quarter reward only: early steps are fitness-free, so
    exploration costs nothing. Anti-settling repricing (exploratory;
    not the locked P0 gate fitness)."""
    T = rewards.shape[0]
    return rewards[-(T // 4):].mean()


FITNESS = {"late": late_weighted_fitness, "q4": q4_fitness}

# ===== changeling/es.py =====
"""Route R1: OpenES, written out in full (no evosax — PREREG_P0 amendment).

Mirrored sampling, centered-rank fitness shaping, Adam ascent. Common task
seeds AND rollout randomness across the population each generation (full
antithetic CRN: mirror pairs differ only in theta, so the dominant noise term
— the Bernoulli reward draws — cancels in F+ - F-).
"""
from functools import partial

import jax
import jax.numpy as jnp
from jax.flatten_util import ravel_pytree



def centered_ranks(f):
    ranks = jnp.argsort(jnp.argsort(f)).astype(jnp.float32)
    return ranks / (f.shape[0] - 1) - 0.5


def adam_init(dim):
    return dict(m=jnp.zeros(dim), v=jnp.zeros(dim), t=jnp.int32(0))


def adam_ascend(theta, grad, st, lr, b1=0.9, b2=0.999, eps=1e-8):
    t = st["t"] + 1
    m = b1 * st["m"] + (1 - b1) * grad
    v = b2 * st["v"] + (1 - b2) * grad ** 2
    mhat = m / (1 - b1 ** t)
    vhat = v / (1 - b2 ** t)
    theta = theta + lr * mhat / (jnp.sqrt(vhat) + eps)
    return theta, dict(m=m, v=v, t=t)


def make_gen_step(env, unravel, pop, n_lifetimes, sigma, lr,
                  fitness_fn=late_weighted_fitness, step=None, ponder_cost=0.0,
                  iface_fn=None):
    """Returns jitted (theta, adam_state, key) -> (theta', adam_state', stats).

    `step` is a B1 step_fn (looped.make_step); None -> legacy gru. `ponder_cost`
    is the −c·mean_t E[K] compute tax folded into ES fitness (the adaptive-K
    pressure). ponder_cost=0.0 + legacy step keeps member_fitness bitwise-identical
    to the pre-B1 harness (e_k≡1, and f − 0.0·1.0 == f), so G0-A reproduces.

    `iface_fn` (B2) samples a per-lifetime interface (P, perm); None -> no
    randomization (byte-identical). Interfaces are drawn once per generation from a
    DISJOINT fold and SHARED across the population — so each antithetic mirror pair
    still differs only in theta (CRN intact), and the interface-key stream never
    perturbs the eps/task/roll splits (alpha=None reproduces G0-A exactly)."""
    assert pop % 2 == 0

    def member_fitness(theta_flat, tasks, roll_keys, ifaces):
        params = unravel(theta_flat)

        def one(task, k, iface):
            rewards, _, _, e_ks = rollout(env, params, task, k, step=step,
                                          iface=iface)
            return fitness_fn(rewards) - ponder_cost * e_ks.mean()

        if iface_fn is None:
            return jax.vmap(lambda t, k: one(t, k, None))(tasks, roll_keys).mean()
        return jax.vmap(one)(tasks, roll_keys, ifaces).mean()

    def gen_step(theta, adam_state, key):
        # interface keys from a disjoint fold (does NOT consume the split below)
        ifaces = None
        if iface_fn is not None:
            ik = jax.random.split(jax.random.fold_in(key, IFACE_FOLD), n_lifetimes)
            ifaces = jax.vmap(iface_fn)(ik)
        key, ke, kt, kr = jax.random.split(key, 4)
        dim = theta.shape[0]
        eps = jax.random.normal(ke, (pop // 2, dim))
        thetas = jnp.concatenate([theta + sigma * eps, theta - sigma * eps])
        tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n_lifetimes))
        # shared across the population (hence across each antithetic pair): the
        # only difference between F+ and F- is then the theta perturbation
        roll_keys = jax.random.split(kr, n_lifetimes)
        fits = jax.vmap(member_fitness, in_axes=(0, None, None, None))(
            thetas, tasks, roll_keys, ifaces)
        shaped = centered_ranks(fits)
        grad = jnp.concatenate([eps, -eps]).T @ shaped / (pop * sigma)
        theta, adam_state = adam_ascend(theta, grad, adam_state, lr)
        stats = dict(fit_mean=fits.mean(), fit_max=fits.max(), fit_std=fits.std())
        return theta, adam_state, stats

    return jax.jit(gen_step)


def flatten_params(params):
    theta, unravel = ravel_pytree(params)
    return theta, unravel

# ===== changeling/evaluate.py =====
"""Gate metrics on held-out lifetimes, plus standing controls C4/C5.

Held-out = eval key space disjoint from training (EVAL_FOLD offset).
Reported per condition:
  reward_q1/q4 — first/final-quarter mean reward
  slope        — q4 - q1 (within-lifetime improvement, the primary endpoint)
  gate_q4      — final-quarter gate metric (bandit: best-arm rate;
                 catch: episode success rate among completed episodes)
"""
import jax
import jax.numpy as jnp


EVAL_FOLD = 10_000_000


def eval_suite(env, params, n=100, seed=0, c4=False, c5=False, c6=False, step=None,
               iface_fn=None):
    key = jax.random.fold_in(jax.random.PRNGKey(seed), EVAL_FOLD)
    kt, kr = jax.random.split(key)
    tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n))
    keys = jax.random.split(kr, n)

    if iface_fn is None:
        def one(task, k):
            return rollout(env, params, task, k, c4=c4, c5=c5, c6=c6, step=step)
        rewards, metrics, dones, e_ks = jax.vmap(one)(tasks, keys)
    else:
        # NOVEL held-out interfaces: drawn from EVAL_FOLD ∘ IFACE_FOLD, disjoint
        # from training interfaces (train keys ∘ IFACE_FOLD). Does not touch kt/kr.
        ik = jax.random.split(jax.random.fold_in(key, IFACE_FOLD), n)
        ifaces = jax.vmap(iface_fn)(ik)

        def one(task, k, iface):
            return rollout(env, params, task, k, c4=c4, c5=c5, c6=c6, step=step,
                           iface=iface)
        rewards, metrics, dones, e_ks = jax.vmap(one)(tasks, keys, ifaces)
    T = rewards.shape[1]
    q = T // 4
    q1, q4 = rewards[:, :q], rewards[:, -q:]
    # gate metric averaged over completed episodes in the final quarter
    m4, d4 = metrics[:, -q:], dones[:, -q:]
    gate_q4 = jnp.sum(m4 * d4) / jnp.maximum(jnp.sum(d4), 1.0)
    # per-lifetime slope sign test (Gate 1 locked statistic; one-sided
    # binomial, ties dropped)
    slopes = q4.mean(axis=1) - q1.mean(axis=1)
    n_pos = int((slopes > 0).sum())
    n_eff = int((slopes != 0).sum())
    return dict(
        reward_q1=float(q1.mean()),
        reward_q4=float(q4.mean()),
        slope=float(q4.mean() - q1.mean()),
        slope_pos_frac=n_pos / max(n_eff, 1),
        slope_sign_p=_binom_tail(n_pos, n_eff),
        gate_q4=float(gate_q4),
        # K-collapse observable (risk #2): mean adaptive-K over the lifetime.
        # ≡1.0 on the legacy substrate; the tripwire wants final-quarter E[K]>1.5.
        e_k_mean=float(e_ks.mean()),
        e_k_q4=float(e_ks[:, -q:].mean()),
    )


def _binom_tail(k, n):
    """P(X >= k), X ~ Binomial(n, 0.5)."""
    from math import comb
    if n == 0:
        return 1.0
    return sum(comb(n, i) for i in range(k, n + 1)) / 2 ** n


def full_eval(env, params, n=100, seed=0, step=None, iface_fn=None):
    """Main condition plus PREREG controls. `step` is a B1 step_fn (looped path);
    None grades the legacy gru substrate. `iface_fn` (B2) grades under NOVEL
    held-out interfaces; None grades the un-randomized (α=0-equivalent) protocol.
    All conditions share the same held-out interface draw so controls are
    comparable to main."""
    return dict(
        main=eval_suite(env, params, n, seed, step=step, iface_fn=iface_fn),
        c4_coin_reward=eval_suite(env, params, n, seed, c4=True, step=step,
                                  iface_fn=iface_fn),
        c5_no_memory=eval_suite(env, params, n, seed, c5=True, step=step,
                                iface_fn=iface_fn),
        c6_full_amnesia=eval_suite(env, params, n, seed, c6=True, step=step,
                                   iface_fn=iface_fn),
    )

# ===== changeling/train.py =====
"""Generation loop with jsonl logging and npz checkpoint/resume."""
import json
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np



def init_core(key, config):
    """The R1 substrate params: looped core (halt+value heads) when config['loop'],
    else the plain GRU. The looped path is a strict superset (K_max=1 ≡ GRU)."""
    if config.get("loop", False):
        return init_looped(key, hidden=config["hidden"])
    return init_gru(key, hidden=config["hidden"])


def save_ckpt(path, theta, adam_state, key, gen, config, best_gate=-1.0):
    np.savez(
        path,
        theta=np.asarray(theta),
        adam_m=np.asarray(adam_state["m"]),
        adam_v=np.asarray(adam_state["v"]),
        adam_t=np.asarray(adam_state["t"]),
        key=np.asarray(key),
        gen=gen,
        config=json.dumps(config),
        best_gate=np.float32(best_gate),
    )


def load_ckpt(path):
    z = np.load(path, allow_pickle=False)
    adam_state = dict(m=jnp.asarray(z["adam_m"]), v=jnp.asarray(z["adam_v"]),
                      t=jnp.int32(z["adam_t"]))
    # best_gate persisted since the resume-clobbers-ckpt_best fix; default for
    # checkpoints written before it (back-compat with existing npz).
    best_gate = float(z["best_gate"]) if "best_gate" in z.files else -1.0
    return (jnp.asarray(z["theta"]), adam_state, jnp.asarray(z["key"]),
            int(z["gen"]), json.loads(str(z["config"])), best_gate)


# Keys allowed to differ across a resume: survivability / logging cadence knobs
# that do NOT define the objective or training distribution. Everything else must
# match the saved config, or the resume silently optimizes a different problem
# from the saved theta (and the next ckpt overwrites the provenance).
_RESUME_FREE = {"max_seconds", "stop_gate", "stop_slope_pos", "updates", "gens",
                "out", "log_every", "eval_every", "ckpt_every"}


def assert_resume_cfg(saved_cfg, config):
    for k in config:
        if k in _RESUME_FREE:
            continue
        assert saved_cfg.get(k) == config[k], (
            f"resume config mismatch on {k!r}: saved={saved_cfg.get(k)!r} "
            f"new={config[k]!r} (objective-determining keys must match)")


def assert_pure_gate(config, eval_env):
    """If the training distribution is non-uniform (a curriculum: mix>0 or
    needle), the eval/gate env MUST be the pure gate task — otherwise gate_q4 is
    silently graded on an easier distribution (inflation, possible false PASS)."""
    ek = config.get("env_kwargs", {})
    if ek.get("mix", 0) > 0 or ek.get("needle", False):
        eek = config.get("eval_env_kwargs", None)
        assert (eek is not None and eek.get("mix", 0) == 0
                and not eek.get("needle", False)), (
            f"training distribution is non-uniform (env_kwargs={ek}) but "
            f"eval_env_kwargs={eek} is not the pure gate task")


def train(config, resume=None):
    out = Path(config["out"])
    out.mkdir(parents=True, exist_ok=True)
    env = ENVS[config["env"]](**config.get("env_kwargs", {}))
    # eval/gate listens to the pure gate task, which may differ from a curriculum
    # training distribution (mirrors ppo.py so ES grades correctly under mix>0).
    eval_env = ENVS[config["env"]](**config.get("eval_env_kwargs",
                                                config.get("env_kwargs", {})))
    assert_pure_gate(config, eval_env)

    step = make_step(config)
    ponder_cost = config.get("ponder_cost", 0.0)
    iface_fn = make_iface_fn(config, for_eval=False)        # B2 train interfaces
    eval_iface_fn = make_iface_fn(config, for_eval=True)    # held-out eval interfaces

    if resume:
        theta, adam_state, key, start_gen, saved_cfg, best_gate = load_ckpt(resume)
        assert_resume_cfg(saved_cfg, config)
        _, unravel = flatten_params(
            init_core(jax.random.PRNGKey(0), config))
        print(f"resumed gen={start_gen} from {resume} (best_gate={best_gate:.3f})")
    else:
        key = jax.random.PRNGKey(config["seed"])
        key, ki = jax.random.split(key)
        params = init_core(ki, config)
        theta, unravel = flatten_params(params)
        adam_state = adam_init(theta.shape[0])
        start_gen = 0
        best_gate = -1.0
        # C1 control: the random-init agent's eval, logged once up front
        c1 = full_eval(eval_env, unravel(theta), n=config["eval_n"],
                       seed=config["seed"], step=step, iface_fn=eval_iface_fn)
        _log(out, dict(gen=-1, condition="c1_random_init", **_flat(c1)))

    gen_step = make_gen_step(env, unravel, config["pop"],
                             config["n_lifetimes"], config["sigma"],
                             config["lr"],
                             fitness_fn=FITNESS[config.get("fitness", "late")],
                             step=step, ponder_cost=ponder_cost, iface_fn=iface_fn)
    print(f"env={env['name']} dim={theta.shape[0]} pop={config['pop']} "
          f"M={config['n_lifetimes']} T={env['T']}")
    print(f"R1 grades gate on eval_env={eval_env['name']} "
          f"kwargs={config.get('eval_env_kwargs', config.get('env_kwargs', {}))}")

    # survivability knobs (both optional, json-safe):
    #   max_seconds    — exit cleanly (checkpoint saved) before a session cap
    #   stop_gate      — stop once eval main.gate_q4 >= this
    #   stop_slope_pos — additionally require eval main.slope > 0 to stop
    max_seconds = config.get("max_seconds")
    stop_gate = config.get("stop_gate")
    stop_slope_pos = config.get("stop_slope_pos", False)

    t0 = time.time()
    for gen in range(start_gen, config["gens"]):
        if max_seconds is not None and time.time() - t0 > max_seconds:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen, config,
                      best_gate=best_gate)
            print(f"wall-clock budget reached at gen {gen}; checkpointed, exiting")
            break
        key, kg = jax.random.split(key)
        theta, adam_state, stats = gen_step(theta, adam_state, kg)
        if (gen + 1) % config["log_every"] == 0:
            row = dict(gen=gen, sec=round(time.time() - t0, 1),
                       **{k: float(v) for k, v in stats.items()})
            _log(out, row)
            print(row)
        if (gen + 1) % config["eval_every"] == 0 or gen + 1 == config["gens"]:
            ev = full_eval(eval_env, unravel(theta), n=config["eval_n"],
                           seed=config["seed"], step=step, iface_fn=eval_iface_fn)
            _log(out, dict(gen=gen, **_flat(ev)))
            print(f"  eval g{gen}: main={ev['main']} "
                  f"c4={ev['c4_coin_reward']['gate_q4']:.3f} "
                  f"c5={ev['c5_no_memory']['gate_q4']:.3f}")
            if ev["main"]["gate_q4"] > best_gate:
                best_gate = ev["main"]["gate_q4"]
                save_ckpt(out / "ckpt_best.npz", theta, adam_state, key,
                          gen + 1, config, best_gate=best_gate)
                print(f"  new best gate_q4={best_gate:.3f} -> ckpt_best.npz")
            if (stop_gate is not None and ev["main"]["gate_q4"] >= stop_gate
                    and (not stop_slope_pos or ev["main"]["slope"] > 0)):
                save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen + 1, config,
                          best_gate=best_gate)
                print(f"stop criterion reached at gen {gen}; checkpointed, exiting")
                break
        if (gen + 1) % config["ckpt_every"] == 0 or gen + 1 == config["gens"]:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen + 1, config,
                      best_gate=best_gate)

    return theta, unravel


def _flat(ev):
    return {f"{cond}.{k}": v for cond, d in ev.items() for k, v in d.items()}


def _log(out, row):
    with open(out / "log.jsonl", "a") as f:
        f.write(json.dumps(row) + "\n")

# ===== changeling/ppo.py =====
"""Route R2: PPO-RL^2 (Duan et al. 2016 protocol, clipped PPO objective).

Whole lifetimes are the trajectories; BPTT through the full lifetime; value
function does NOT reset at episode boundaries (the objective is lifetime
return). Training rewards carry the same late-weight w_t as R1 fitness, but the
selection pressures are NOT identical: R1 ranks the undiscounted weighted-average
fitness sum(w_t·r_t)/sum(w_t), whereas here w_t enters the per-step reward and is
then reshaped by the γ-discounted GAE — the effective per-step weight is γ^t·w_t,
which for γ=0.99 over T=200 tilts EARLY, the reverse of R1's late tilt. This is a
DECLARED confounder of the R1-vs-R2 slope comparison (PREREG_P0 D3), to be
controlled in the Phase-1 route-scaling protocol; it does not affect any
single-route eval (eval is untouched and uses raw rewards).

The deploy artifact is params["gru"] — the same pure S1 substrate as R1.
The value head exists only at training time (a connector, in SPEC terms).
"""
import json
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
from jax.flatten_util import ravel_pytree



def init_ppo_params(key, hidden=128, cfg=None):
    """Legacy: a plain GRU core + a separate top-level value head (a training-only
    connector). Looped (cfg['loop']): the looped core, whose halt+value heads live
    INSIDE params['gru'] — commit_v IS the state-value, so no top-level Wv/bv."""
    cfg = cfg or {}
    if cfg.get("loop", False):
        return {"gru": init_looped(key, hidden)}
    kg, kv = jax.random.split(key)
    return {
        "gru": init_gru(kg, hidden),
        "Wv": jax.random.normal(kv, (hidden, 1)) / jnp.sqrt(hidden),
        "bv": jnp.zeros(1),
    }


def collect(env, params, task, key, reward_scale, step, loop, iface=None):
    """One lifetime under the current policy. Returns everything the loss
    needs to recompute the forward pass exactly (teacher forcing on xs).
    Rewards come back late-weighted (PREREG_P0 selection pressure) and
    scaled so discounted returns are O(1) — otherwise the value-loss
    gradient through the shared trunk drowns the policy gradient.

    `step` is a B1 step_fn (looped.make_step). Legacy: sample from raw logits,
    value from the top-level head — byte-identical to the pre-B1 collect. Looped:
    sample from the marginal commit dist; the state-value IS commit_v.

    `iface` (B2) is the per-lifetime (P, perm). xs store the PROJECTED obs and the
    RAW action, so the loss replay (teacher-forced on xs) stays the exact forward
    pass — the collect==forward lynchpin is preserved under randomization."""
    T = env["T"]
    if iface is not None:
        P, perm = iface
    key, k0 = jax.random.split(key)
    state0, obs0 = env["reset"](k0, task)
    h0 = jnp.zeros(hidden_size(params["gru"]))
    carry0 = (h0, state0, obs0, jnp.zeros(N_ACT), jnp.float32(0.0),
              jnp.float32(1.0), key)

    def step_fn(carry, w_t):
        h, state, obs, last_a, last_r, boundary, key = carry
        key, ka, kr, kres = jax.random.split(key, 4)
        obs_in = P @ obs if iface is not None else obs
        x = jnp.concatenate([obs_in, last_a, jnp.array([last_r, boundary])])
        h, sample_score, logp_all, value, aux = step(params["gru"], h, x)
        a = jax.random.categorical(ka, sample_score)
        a_env = perm[a] if iface is not None else a
        v = value if loop else (h @ params["Wv"] + params["bv"])[0]
        state, obs, r, done, _ = env["step"](state, a_env, kr, task)
        rs_state, rs_obs = env["reset"](kres, task)
        state = jax.tree_util.tree_map(
            lambda new, old: jnp.where(done, new, old), rs_state, state)
        obs = jnp.where(done, rs_obs, obs)
        carry = (h, state, obs, jax.nn.one_hot(a, N_ACT), r,
                 done.astype(jnp.float32), key)
        out = (x, a, logp_all[a], v, r * w_t * reward_scale)
        return carry, out

    w = jnp.linspace(0.5, 1.5, T)
    _, (xs, acts, logps, vals, rews) = jax.lax.scan(step_fn, carry0, w)
    return xs, acts, logps, vals, rews


def gae(rews, vals, gamma, lam):
    """Advantages over the whole lifetime; terminal value 0 (lifetime over)."""
    vals_next = jnp.concatenate([vals[1:], jnp.zeros(1)])
    deltas = rews + gamma * vals_next - vals

    def back(carry, delta):
        carry = delta + gamma * lam * carry
        return carry, carry

    _, adv = jax.lax.scan(back, jnp.float32(0.0), deltas, reverse=True)
    return adv, adv + vals  # advantages, returns


def make_update_step(env, unravel, cfg):
    n_life = cfg["n_lifetimes"]
    gamma, lam = cfg["gamma"], cfg["lam"]
    clip, vf_c, ent_c = cfg["clip"], cfg["vf_coef"], cfg["ent_coef"]

    # B1 looped substrate (trace-time branch: loop=False emits the exact legacy
    # graph). When loop=True the policy is the marginal commit mixture, the value
    # is per-turn v_k reconstructed (PonderNet L_rec), and a KL-to-geometric prior
    # (weight kl_coef) regularizes the halting distribution toward E[K]=1/lam_p.
    loop = cfg.get("loop", False)
    step = make_step(cfg)
    k_max, k_min = int(cfg.get("k_max", 1)), int(cfg.get("k_min", 2))
    lam_p, kl_c = float(cfg.get("lam_p", 0.2)), float(cfg.get("kl_coef", 0.0))
    iface_fn = make_iface_fn(cfg, for_eval=False)   # B2 train-interface sampler

    rew_scale = cfg.get("reward_scale", 1.0 - cfg["gamma"])
    # D3 landmine: at gamma=1.0 (route-reconciled config) the default 1-gamma=0
    # would zero every training reward. Require an explicit positive scale.
    assert rew_scale > 0, (
        f"reward_scale={rew_scale} (<=0) zeros every training reward; with "
        f"gamma={cfg['gamma']} the default 1-gamma is non-positive — pass "
        f"reward_scale explicitly (D3 reconciliation uses 1/T at gamma=1.0).")

    def batch_collect(theta, key):
        params = unravel(theta)
        kt, kr = jax.random.split(key)
        tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n_life))
        keys = jax.random.split(kr, n_life)
        if iface_fn is None:
            xs, acts, logps, vals, rews = jax.vmap(
                lambda t, k: collect(env, params, t, k, rew_scale, step, loop))(
                    tasks, keys)
        else:
            # interface keys from a disjoint fold (does NOT consume kt/kr above)
            ik = jax.random.split(jax.random.fold_in(key, IFACE_FOLD), n_life)
            ifaces = jax.vmap(iface_fn)(ik)
            xs, acts, logps, vals, rews = jax.vmap(
                lambda t, k, i: collect(env, params, t, k, rew_scale, step, loop,
                                        iface=i))(tasks, keys, ifaces)
        adv, rets = jax.vmap(lambda r, v: gae(r, v, gamma, lam))(rews, vals)
        adv = (adv - adv.mean()) / (adv.std() + 1e-8)
        return xs, acts, logps, adv, rets

    def loss_fn(theta, batch):
        params = unravel(theta)
        xs, acts, logps_old, adv, rets = batch
        h0 = jnp.zeros(hidden_size(params["gru"]))

        if loop:
            def forward(xs_one):
                def st(h, x):
                    h, _ss, logp_all, value, aux = step(params["gru"], h, x)
                    return h, (logp_all, value, aux["p"], aux["v_k"], aux["E_K"])
                _, outs = jax.lax.scan(st, h0, xs_one)
                return outs  # (logp_all, v, p, v_k, E_K)

            logp_all, v, p, v_k, e_k = jax.vmap(forward)(xs)
            #   logp_all (B,T,A)  v (B,T)  p (B,T,K)  v_k (B,T,K)  e_k (B,T)
            logp = jnp.take_along_axis(logp_all, acts[..., None], -1)[..., 0]
            ratio = jnp.exp(logp - logps_old)
            pg = jnp.minimum(ratio * adv,
                             jnp.clip(ratio, 1 - clip, 1 + clip) * adv).mean()
            # per-turn value reconstruction, halting-weighted (PonderNet L_rec):
            # each micro-turn's value head is regressed to the lifetime return,
            # weighted by that turn's commit mass p_k.
            vloss = (p * (v_k - rets[..., None]) ** 2).sum(-1).mean()
            ent = -(jnp.exp(logp_all) * logp_all).sum(-1).mean()
            kl_fn = lambda pp: kl_to_geometric(pp, lam_p, k_max, k_min)
            klr = jax.vmap(jax.vmap(kl_fn))(p).mean()
            loss = -(pg - vf_c * vloss + ent_c * ent) + kl_c * klr
            return loss, dict(pg=pg, v=vloss, ent=ent, kl=klr, e_k=e_k.mean())

        def forward(xs_one):
            def st(h, x):
                h, _ss, logp_all, _value, _aux = step(params["gru"], h, x)
                v = (h @ params["Wv"] + params["bv"])[0]
                return h, (logp_all, v)
            _, (logp_all, v) = jax.lax.scan(st, h0, xs_one)
            return logp_all, v

        logp_all, v = jax.vmap(forward)(xs)  # (B,T,A), (B,T)
        logp = jnp.take_along_axis(logp_all, acts[..., None], -1)[..., 0]
        ratio = jnp.exp(logp - logps_old)
        pg = jnp.minimum(ratio * adv,
                         jnp.clip(ratio, 1 - clip, 1 + clip) * adv).mean()
        vloss = 0.5 * ((v - rets) ** 2).mean()
        ent = -(jnp.exp(logp_all) * logp_all).sum(-1).mean()
        return -(pg - vf_c * vloss + ent_c * ent), dict(pg=pg, v=vloss, ent=ent)

    grad_fn = jax.value_and_grad(loss_fn, has_aux=True)

    def epoch_step(theta, adam_state, batch):
        (loss, aux), grad = grad_fn(theta, batch)
        gnorm = jnp.sqrt(jnp.sum(grad ** 2))
        grad = grad * jnp.minimum(1.0, cfg["max_grad_norm"] / (gnorm + 1e-8))
        theta, adam_state = adam_ascend(theta, -grad, adam_state, cfg["lr"])
        return theta, adam_state, loss, dict(aux, gnorm=gnorm)

    return jax.jit(batch_collect), jax.jit(epoch_step)


def train_ppo(config, resume=None):
    out = Path(config["out"])
    out.mkdir(parents=True, exist_ok=True)
    env = ENVS[config["env"]](**config.get("env_kwargs", {}))
    # eval (and therefore stop_gate) listens to the GATE task, which may
    # differ from the training distribution (e.g. mixture curricula)
    eval_env = ENVS[config["env"]](**config.get("eval_env_kwargs",
                                                config.get("env_kwargs", {})))
    assert_pure_gate(config, eval_env)
    print(f"R2 grades gate on eval_env={eval_env['name']} "
          f"kwargs={config.get('eval_env_kwargs', config.get('env_kwargs', {}))}")

    step = make_step(config)
    eval_iface_fn = make_iface_fn(config, for_eval=True)   # held-out eval interfaces

    if resume:
        theta, adam_state, key, start_up, saved_cfg, best_gate = load_ckpt(resume)
        assert_resume_cfg(saved_cfg, config)
        _, unravel = ravel_pytree(
            init_ppo_params(jax.random.PRNGKey(0), config["hidden"], config))
        print(f"resumed update={start_up} from {resume} (best_gate={best_gate:.3f})")
    else:
        key = jax.random.PRNGKey(config["seed"])
        key, ki = jax.random.split(key)
        theta, unravel = ravel_pytree(init_ppo_params(ki, config["hidden"], config))
        adam_state = adam_init(theta.shape[0])
        start_up = 0
        best_gate = -1.0

    batch_collect, epoch_step = make_update_step(env, unravel, config)
    print(f"R2 PPO env={env['name']} dim={theta.shape[0]} "
          f"B={config['n_lifetimes']} T={env['T']}")

    max_seconds = config.get("max_seconds")
    stop_gate = config.get("stop_gate")
    stop_slope_pos = config.get("stop_slope_pos", False)

    t0 = time.time()
    for up in range(start_up, config["updates"]):
        if max_seconds is not None and time.time() - t0 > max_seconds:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, up, config,
                      best_gate=best_gate)
            print(f"wall-clock budget reached at update {up}; exiting")
            break
        key, kc = jax.random.split(key)
        batch = batch_collect(theta, kc)
        for _ in range(config["epochs"]):
            theta, adam_state, loss, aux = epoch_step(theta, adam_state, batch)
        if (up + 1) % config["log_every"] == 0:
            row = dict(update=up, sec=round(time.time() - t0, 1),
                       loss=float(loss), pg=float(aux["pg"]),
                       vloss=float(aux["v"]), ent=float(aux["ent"]),
                       gnorm=float(aux["gnorm"]))
            if "kl" in aux:  # looped substrate diagnostics
                row["kl"] = float(aux["kl"])
                row["e_k"] = float(aux["e_k"])
            _log(out, row)
            print(row)
        if (up + 1) % config["eval_every"] == 0 or up + 1 == config["updates"]:
            ev = full_eval(eval_env, unravel(theta)["gru"], n=config["eval_n"],
                           seed=config["seed"], step=step, iface_fn=eval_iface_fn)
            _log(out, dict(update=up, **_flat(ev)))
            print(f"  eval u{up}: main={ev['main']} "
                  f"c4={ev['c4_coin_reward']['gate_q4']:.3f} "
                  f"c5={ev['c5_no_memory']['gate_q4']:.3f}")
            if ev["main"]["gate_q4"] > best_gate:
                best_gate = ev["main"]["gate_q4"]
                save_ckpt(out / "ckpt_best.npz", theta, adam_state, key,
                          up + 1, config, best_gate=best_gate)
                print(f"  new best gate_q4={best_gate:.3f} -> ckpt_best.npz")
            if (stop_gate is not None and ev["main"]["gate_q4"] >= stop_gate
                    and (not stop_slope_pos or ev["main"]["slope"] > 0)):
                save_ckpt(out / "ckpt.npz", theta, adam_state, key, up + 1, config,
                          best_gate=best_gate)
                print(f"stop criterion reached at update {up}; exiting")
                break
        if (up + 1) % config["ckpt_every"] == 0 or up + 1 == config["updates"]:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, up + 1, config,
                      best_gate=best_gate)

    return theta, unravel


# ===== kernel main (route: es) =====
if __name__ == "__main__":
    import glob
    import os

    ROUTE = "es"
    GATE_BANDIT = 0.672  # 0.90 x Thompson reference 0.747 (PREREG deviation D1)
    smoke = os.environ.get("CHANGELING_SMOKE") == "1"
    print("jax devices:", jax.devices())
    base = "/kaggle/working" if os.path.isdir("/kaggle/working") else "runs_kernel"
    wall_start = time.time()
    WALL_BUDGET = 7.5 * 3600  # exit cleanly well inside Kaggle's session cap

    def find_resume(name):
        """Resume from a prior session's checkpoint, attached as a DATASET
        (kernel_sources mounts code, not outputs — probed 2026-06-12)."""
        hits = sorted(h for h in
                      glob.glob("/kaggle/input/**/ckpt.npz", recursive=True)
                      if name in h)
        return hits[0] if hits else None

    if ROUTE == "es":
        common = dict(hidden=128, pop=256, n_lifetimes=8, sigma=0.03, lr=0.02,
                      seed=0, eval_n=100, eval_every=200, log_every=25,
                      ckpt_every=100)
        jobs = [("bandit", dict(gens=3000, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True)),
                ("catch", dict(gens=3000, stop_gate=0.90))]
        trainer = train
    else:
        common = dict(hidden=128, n_lifetimes=64, lr=5e-4, gamma=0.99,
                      lam=0.95, clip=0.2, epochs=4, vf_coef=0.5,
                      ent_coef=0.01, max_grad_norm=0.5, seed=0,
                      eval_n=200, eval_every=250, log_every=50,
                      ckpt_every=250)
        jobs = [("bandit", dict(updates=8000, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True,
                                env_kwargs=dict(mix=0.0),
                                eval_env_kwargs=dict()))]  # stop listens to gate task
        trainer = train_ppo
    if smoke:
        common.update(hidden=32, eval_n=20, eval_every=5, log_every=1,
                      ckpt_every=5)
        gens_key = "gens" if ROUTE == "es" else "updates"
        jobs = [(n, dict(d, **{gens_key: 5})) for n, d in jobs]

    for name, extra in jobs:
        cfg = dict(env=name, out=f"{base}/gate_{name}_es",
                   max_seconds=WALL_BUDGET - (time.time() - wall_start),
                   **common, **extra)
        resume = find_resume(f"gate_{name}_es")
        print(f"\n##### {name} [es]: resume={resume}")
        if resume is None and os.path.isdir("/kaggle/input"):
            for cur, dirs, files in os.walk("/kaggle/input"):
                d = cur.count(os.sep) - 2
                print("  " * d + cur, files[:8])
                if d >= 3:
                    dirs[:] = []
        theta, unravel = trainer(cfg, resume=resume)
        params = unravel(theta) if ROUTE == "es" else unravel(theta)["gru"]
        ev = full_eval(ENVS[name](), params, n=cfg["eval_n"], seed=cfg["seed"])
        m, c4, c5 = ev["main"], ev["c4_coin_reward"], ev["c5_no_memory"]
        print(f"\n=== GATE 0 verdict: {name} [es] ===")
        if name == "bandit":
            print(f"G0-A gate_q4={m['gate_q4']:.3f} (>={GATE_BANDIT}, D1):",
                  "PASS" if m["gate_q4"] >= GATE_BANDIT else "FAIL")
            print(f"G0-A slope={m['slope']:+.4f} (>0):",
                  "PASS" if m["slope"] > 0 else "FAIL")
            print(f"G0-B c4={c4['gate_q4']:.3f} (<=0.225):",
                  "PASS" if c4["gate_q4"] <= 0.225 else "FAIL")
            print(f"G0-C c5={c5['gate_q4']:.3f} (<=0.225):",
                  "PASS" if c5["gate_q4"] <= 0.225 else "FAIL")
        else:
            print(f"G0-D gate_q4={m['gate_q4']:.3f} (>=0.90):",
                  "PASS" if m["gate_q4"] >= 0.90 else "FAIL")
    print("\ntotal wall:", round(time.time() - wall_start), "s")
