#!/usr/bin/env python3
"""Build a self-contained Kaggle kernel script for a Phase 0 gate run.

  python scripts/build_kernel.py                 # R1 ES kernel (bandit+catch)
  python scripts/build_kernel.py --route ppo     # R2 PPO kernel (bandit only)
  python scripts/build_kernel.py --route ppo --session 2 --updates 32000
      # session 2: new slug <base>-s2, attaches session 1's output as a
      # kernel source so find_resume() continues from its checkpoint

Writes kaggle/<slug>/kernel.py + kernel-metadata.json. Intra-package imports
are stripped; module order satisfies all definitions. Re-run after any
package edit."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "changeling"
ORDER = ["__init__.py", "envs.py", "agent.py", "rollout.py", "es.py",
         "evaluate.py", "train.py", "ppo.py"]
INTRA = re.compile(r"^from \.\S* import |^from \. import ")

MAIN = '''

# ===== kernel main (route: {route}) =====
if __name__ == "__main__":
    import glob
    import os

    ROUTE = "{route}"
    GATE_BANDIT = 0.672  # 0.90 x Thompson reference 0.747 (PREREG deviation D1)
    smoke = os.environ.get("CHANGELING_SMOKE") == "1"
    print("jax devices:", jax.devices())
    base = "/kaggle/working" if os.path.isdir("/kaggle/working") else "runs_kernel"
    wall_start = time.time()
    WALL_BUDGET = 7.5 * 3600  # exit cleanly well inside Kaggle's session cap

    def find_resume(name):
        """Resume from a prior session's output attached as a data source."""
        hits = sorted(glob.glob(f"/kaggle/input/*/{{name}}/ckpt.npz")
                      + glob.glob(f"/kaggle/input/*/runs/{{name}}/ckpt.npz"))
        return hits[0] if hits else None

    if ROUTE == "es":
        common = dict(hidden=128, pop=256, n_lifetimes=8, sigma=0.03, lr=0.02,
                      seed=0, eval_n=100, eval_every=200, log_every=25,
                      ckpt_every=100)
        jobs = [("bandit", dict(gens=3000, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True)),
                ("catch", dict(gens=3000, stop_gate=0.90))]
        trainer = train
    else:
        common = dict(hidden=128, n_lifetimes=64, lr=5e-4, gamma=0.99,
                      lam=0.95, clip=0.2, epochs=4, vf_coef=0.5, ent_coef=0.01,
                      max_grad_norm=0.5, seed=0, eval_n=100, eval_every=250,
                      log_every=50, ckpt_every=250)
        jobs = [("bandit", dict(updates={updates}, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True))]
        trainer = train_ppo
    if smoke:
        common.update(hidden=32, eval_n=20, eval_every=5, log_every=1,
                      ckpt_every=5)
        gens_key = "gens" if ROUTE == "es" else "updates"
        jobs = [(n, dict(d, **{{gens_key: 5}})) for n, d in jobs]

    for name, extra in jobs:
        cfg = dict(env=name, out=f"{{base}}/gate_{{name}}_{route}",
                   max_seconds=WALL_BUDGET - (time.time() - wall_start),
                   **common, **extra)
        resume = find_resume(f"gate_{{name}}_{route}")
        print(f"\\n##### {{name}} [{route}]: resume={{resume}}")
        theta, unravel = trainer(cfg, resume=resume)
        params = unravel(theta) if ROUTE == "es" else unravel(theta)["gru"]
        ev = full_eval(ENVS[name](), params, n=cfg["eval_n"], seed=cfg["seed"])
        m, c4, c5 = ev["main"], ev["c4_coin_reward"], ev["c5_no_memory"]
        print(f"\\n=== GATE 0 verdict: {{name}} [{route}] ===")
        if name == "bandit":
            print(f"G0-A gate_q4={{m['gate_q4']:.3f}} (>={{GATE_BANDIT}}, D1):",
                  "PASS" if m["gate_q4"] >= GATE_BANDIT else "FAIL")
            print(f"G0-A slope={{m['slope']:+.4f}} (>0):",
                  "PASS" if m["slope"] > 0 else "FAIL")
            print(f"G0-B c4={{c4['gate_q4']:.3f}} (<=0.225):",
                  "PASS" if c4["gate_q4"] <= 0.225 else "FAIL")
            print(f"G0-C c5={{c5['gate_q4']:.3f}} (<=0.225):",
                  "PASS" if c5["gate_q4"] <= 0.225 else "FAIL")
        else:
            print(f"G0-D gate_q4={{m['gate_q4']:.3f}} (>=0.90):",
                  "PASS" if m["gate_q4"] >= 0.90 else "FAIL")
    print("\\ntotal wall:", round(time.time() - wall_start), "s")
'''


def build(route, session=1, updates=8000):
    base = "changeling-p0-gate" if route == "es" else "changeling-p0-r2"
    slug = base if session == 1 else f"{base}-s{session}"
    prev = base if session == 2 else f"{base}-s{session - 1}"
    sources = [] if session == 1 else [f"asystemoffields/{prev}"]
    parts = ['"""changeling Phase 0 gate runs — AUTOGENERATED by '
             'scripts/build_kernel.py; do not edit by hand. See SPEC.md / '
             'PREREG_P0.md in the repo."""']
    for fname in ORDER:
        body = "\n".join(l for l in (PKG / fname).read_text().splitlines()
                         if not INTRA.match(l))
        parts.append(f"\n# ===== changeling/{fname} =====\n{body}")
    parts.append(MAIN.format(route=route, updates=updates))
    out_dir = ROOT / "kaggle" / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "kernel.py").write_text("\n".join(parts))
    (out_dir / "kernel-metadata.json").write_text(json.dumps({
        "id": f"asystemoffields/{slug}",
        "title": slug,
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": False,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": sources,
    }, indent=2) + "\n")
    print(f"wrote {out_dir}/kernel.py "
          f"({(out_dir / 'kernel.py').stat().st_size} bytes)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--route", choices=["es", "ppo"], default="es")
    ap.add_argument("--session", type=int, default=1)
    ap.add_argument("--updates", type=int, default=8000)
    a = ap.parse_args()
    build(a.route, a.session, a.updates)
