"""changeling Phase 0 gate runs — AUTOGENERATED by scripts/build_kernel.py; do not edit by hand. See SPEC.md / PREREG_P0.md in the repo."""

# ===== changeling/__init__.py =====
"""changeling — breeding transferable in-context learners. See SPEC.md."""

OBS_DIM = 64
N_ACT = 8
IN_DIM = OBS_DIM + N_ACT + 2  # obs, onehot(last action), last reward, boundary bit

# ===== changeling/envs.py =====
"""Phase 0 environments in pure JAX.

An env is a dict of pure functions sharing the fixed interface protocol
(SPEC section 2): obs padded to OBS_DIM, actions in [0, N_ACT).

  sample_task(key) -> task            (per-lifetime parameters)
  reset(key, task) -> (state, obs)    (per-episode)
  step(state, a, key, task) -> (state, obs, reward, done, metric)

`metric` is the env's gate statistic (bandit: pulled best arm; catch: success,
nonzero only on terminal steps). T is lifetime length in steps.
"""
import jax
import jax.numpy as jnp



def bandit_env(n_arms=8, lifetime=200, needle=False, mix=0.0):
    """Bernoulli bandit. Default: p_i ~ U(0,1) per lifetime (forgiving —
    second-best is typically close to best, so satisficing nearly pays).
    needle=True: one arm at 0.9, the rest at 0.1 — finding the needle is
    constitutive of success; settling pays 0.1. mix=p: each lifetime is a
    needle task w.p. p, else uniform (curriculum contrast). One-step episodes."""
    assert 2 <= n_arms <= 8

    def sample_task(key):
        if needle:
            pos = jax.random.randint(key, (), 0, n_arms)
            return jnp.where(jnp.arange(n_arms) == pos, 0.9, 0.1)
        return jax.random.uniform(key, (n_arms,))

    if mix > 0:
        base = sample_task

        def sample_task(key):  # noqa: F811 — mixture wraps the base sampler
            ku, kn, kc = jax.random.split(key, 3)
            pos = jax.random.randint(kn, (), 0, n_arms)
            needle_p = jnp.where(jnp.arange(n_arms) == pos, 0.9, 0.1)
            return jnp.where(jax.random.bernoulli(kc, mix),
                             needle_p, base(ku))

    def reset(key, task):
        return (), jnp.zeros(OBS_DIM)

    def step(state, a, key, task):
        a_eff = a % n_arms  # surplus interface actions wrap onto real arms
        r = jax.random.bernoulli(key, task[a_eff]).astype(jnp.float32)
        metric = (a_eff == jnp.argmax(task)).astype(jnp.float32)
        return (), jnp.zeros(OBS_DIM), r, jnp.bool_(True), metric

    return dict(sample_task=sample_task, reset=reset, step=step,
                T=lifetime, name=f"bandit{n_arms}")


def catch_env(episodes=32):
    """bsuite-style Catch: 10x5 board, ball falls one row/step, paddle on the
    bottom row. +1 catch / -1 miss on the terminal step. 9-step episodes."""
    ROWS, COLS = 10, 5

    def _obs(state):
        ball_row, ball_col, paddle = state
        grid = jnp.zeros((ROWS, COLS))
        grid = grid.at[ball_row, ball_col].set(1.0)
        grid = grid.at[ROWS - 1, paddle].set(1.0)
        flat = grid.reshape(-1)
        return jnp.concatenate([flat, jnp.zeros(OBS_DIM - flat.shape[0])])

    def sample_task(key):
        return jnp.zeros(())  # no task variation in P0

    def reset(key, task):
        col = jax.random.randint(key, (), 0, COLS)
        state = (jnp.int32(0), col, jnp.int32(COLS // 2))
        return state, _obs(state)

    def step(state, a, key, task):
        ball_row, ball_col, paddle = state
        move = jnp.where(a == 0, -1, jnp.where(a == 2, 1, 0))  # 3..7 -> stay
        paddle = jnp.clip(paddle + move, 0, COLS - 1)
        ball_row = ball_row + 1
        done = ball_row >= ROWS - 1
        caught = (ball_col == paddle).astype(jnp.float32)
        r = jnp.where(done, 2.0 * caught - 1.0, 0.0)
        state = (ball_row, ball_col, paddle)
        return state, _obs(state), r, done, jnp.where(done, caught, 0.0)

    return dict(sample_task=sample_task, reset=reset, step=step,
                T=episodes * (ROWS - 1), name="catch")


ENVS = {"bandit": bandit_env, "catch": catch_env}

# ===== changeling/agent.py =====
"""S1 substrate: plain GRU, pure JAX. Params are a flat dict pytree."""
import jax
import jax.numpy as jnp



def init_gru(key, hidden=128, in_dim=IN_DIM, out_dim=N_ACT):
    ks = jax.random.split(key, 7)
    s_in, s_h = 1.0 / jnp.sqrt(in_dim), 1.0 / jnp.sqrt(hidden)

    def mat(k, shape, scale):
        return jax.random.normal(k, shape) * scale

    return {
        "Wxz": mat(ks[0], (in_dim, hidden), s_in), "Whz": mat(ks[1], (hidden, hidden), s_h),
        "bz": jnp.zeros(hidden),
        "Wxr": mat(ks[2], (in_dim, hidden), s_in), "Whr": mat(ks[3], (hidden, hidden), s_h),
        "br": jnp.zeros(hidden),
        "Wxh": mat(ks[4], (in_dim, hidden), s_in), "Whh": mat(ks[5], (hidden, hidden), s_h),
        "bh": jnp.zeros(hidden),
        "Wo": mat(ks[6], (hidden, out_dim), s_h), "bo": jnp.zeros(out_dim),
    }


def gru_step(p, h, x):
    z = jax.nn.sigmoid(x @ p["Wxz"] + h @ p["Whz"] + p["bz"])
    r = jax.nn.sigmoid(x @ p["Wxr"] + h @ p["Whr"] + p["br"])
    hh = jnp.tanh(x @ p["Wxh"] + (r * h) @ p["Whh"] + p["bh"])
    h = (1.0 - z) * h + z * hh
    return h, h @ p["Wo"] + p["bo"]


def hidden_size(params):
    return params["bz"].shape[0]

# ===== changeling/rollout.py =====
"""One lifetime: RL^2 protocol. Memory persists across episodes within a
lifetime; env auto-resets on done (same task). Controls (PREREG_P0):
  c4 — blind the agent's reward *input* with a fair coin (env reward still
       scored); in-context learning should collapse where reward is the only cue.
  c5 — reset hidden state on every episode boundary; memory is the only
       learning mechanism, so this is the no-memory control. NOTE: the RL²
       input channel (last action/reward) still flows — C5 bounds the
       non-recurrent component, not memory absolutely.
  c6 — full amnesia: C5 plus zeroed last-action/last-reward inputs; nothing
       carries across steps. Performance must be exactly chance-level.
"""
import jax
import jax.numpy as jnp



def rollout(env, params, task, key, c4=False, c5=False, c6=False):
    """Returns (rewards, metrics, dones) arrays of shape (T,)."""
    if c6:
        c5 = True
    T = env["T"]
    key, k0 = jax.random.split(key)
    state0, obs0 = env["reset"](k0, task)
    h0 = jnp.zeros(hidden_size(params))
    carry0 = (h0, state0, obs0, jnp.zeros(N_ACT), jnp.float32(0.0),
              jnp.float32(1.0), key)

    def step_fn(carry, _):
        h, state, obs, last_a, last_r, boundary, key = carry
        key, ka, kr, kres, kc4 = jax.random.split(key, 5)
        r_in = jax.random.bernoulli(kc4, 0.5).astype(jnp.float32) if c4 else last_r
        if c6:
            last_a, r_in = jnp.zeros_like(last_a), jnp.float32(0.0)
        x = jnp.concatenate([obs, last_a, jnp.array([r_in, boundary])])
        h, logits = gru_step(params, h, x)
        a = jax.random.categorical(ka, logits)
        state, obs, r, done, metric = env["step"](state, a, kr, task)
        # auto-reset on episode end, same task
        rs_state, rs_obs = env["reset"](kres, task)
        state = jax.tree_util.tree_map(
            lambda new, old: jnp.where(done, new, old), rs_state, state)
        obs = jnp.where(done, rs_obs, obs)
        if c5:
            h = h * (1.0 - done.astype(jnp.float32))
        carry = (h, state, obs, jax.nn.one_hot(a, N_ACT), r,
                 done.astype(jnp.float32), key)
        return carry, (r, metric, done.astype(jnp.float32))

    _, (rewards, metrics, dones) = jax.lax.scan(step_fn, carry0, None, length=T)
    return rewards, metrics, dones


def late_weighted_fitness(rewards):
    """Fitness weights ramp 0.5 -> 1.5 across the lifetime (selects for
    improvement, not just performance). PREREG_P0 locked."""
    T = rewards.shape[0]
    w = jnp.linspace(0.5, 1.5, T)
    return jnp.sum(w * rewards) / jnp.sum(w)


def q4_fitness(rewards):
    """Final-quarter reward only: early steps are fitness-free, so
    exploration costs nothing. Anti-settling repricing (exploratory;
    not the locked P0 gate fitness)."""
    T = rewards.shape[0]
    return rewards[-(T // 4):].mean()


FITNESS = {"late": late_weighted_fitness, "q4": q4_fitness}

# ===== changeling/es.py =====
"""Route R1: OpenES, written out in full (no evosax — PREREG_P0 amendment).

Mirrored sampling, centered-rank fitness shaping, Adam ascent. Common task
seeds across the population each generation (CRN variance reduction).
"""
from functools import partial

import jax
import jax.numpy as jnp
from jax.flatten_util import ravel_pytree



def centered_ranks(f):
    ranks = jnp.argsort(jnp.argsort(f)).astype(jnp.float32)
    return ranks / (f.shape[0] - 1) - 0.5


def adam_init(dim):
    return dict(m=jnp.zeros(dim), v=jnp.zeros(dim), t=jnp.int32(0))


def adam_ascend(theta, grad, st, lr, b1=0.9, b2=0.999, eps=1e-8):
    t = st["t"] + 1
    m = b1 * st["m"] + (1 - b1) * grad
    v = b2 * st["v"] + (1 - b2) * grad ** 2
    mhat = m / (1 - b1 ** t)
    vhat = v / (1 - b2 ** t)
    theta = theta + lr * mhat / (jnp.sqrt(vhat) + eps)
    return theta, dict(m=m, v=v, t=t)


def make_gen_step(env, unravel, pop, n_lifetimes, sigma, lr,
                  fitness_fn=late_weighted_fitness):
    """Returns jitted (theta, adam_state, key) -> (theta', adam_state', stats)."""
    assert pop % 2 == 0

    def member_fitness(theta_flat, tasks, roll_keys):
        params = unravel(theta_flat)

        def one(task, k):
            rewards, _, _ = rollout(env, params, task, k)
            return fitness_fn(rewards)

        return jax.vmap(one)(tasks, roll_keys).mean()

    def gen_step(theta, adam_state, key):
        key, ke, kt, kr = jax.random.split(key, 4)
        dim = theta.shape[0]
        eps = jax.random.normal(ke, (pop // 2, dim))
        thetas = jnp.concatenate([theta + sigma * eps, theta - sigma * eps])
        tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n_lifetimes))
        roll_keys = jax.random.split(kr, pop * n_lifetimes).reshape(
            pop, n_lifetimes, -1)
        fits = jax.vmap(member_fitness, in_axes=(0, None, 0))(
            thetas, tasks, roll_keys)
        shaped = centered_ranks(fits)
        grad = jnp.concatenate([eps, -eps]).T @ shaped / (pop * sigma)
        theta, adam_state = adam_ascend(theta, grad, adam_state, lr)
        stats = dict(fit_mean=fits.mean(), fit_max=fits.max(), fit_std=fits.std())
        return theta, adam_state, stats

    return jax.jit(gen_step)


def flatten_params(params):
    theta, unravel = ravel_pytree(params)
    return theta, unravel

# ===== changeling/evaluate.py =====
"""Gate metrics on held-out lifetimes, plus standing controls C4/C5.

Held-out = eval key space disjoint from training (EVAL_FOLD offset).
Reported per condition:
  reward_q1/q4 — first/final-quarter mean reward
  slope        — q4 - q1 (within-lifetime improvement, the primary endpoint)
  gate_q4      — final-quarter gate metric (bandit: best-arm rate;
                 catch: episode success rate among completed episodes)
"""
import jax
import jax.numpy as jnp


EVAL_FOLD = 10_000_000


def eval_suite(env, params, n=100, seed=0, c4=False, c5=False, c6=False):
    key = jax.random.fold_in(jax.random.PRNGKey(seed), EVAL_FOLD)
    kt, kr = jax.random.split(key)
    tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n))
    keys = jax.random.split(kr, n)

    def one(task, k):
        return rollout(env, params, task, k, c4=c4, c5=c5, c6=c6)

    rewards, metrics, dones = jax.vmap(one)(tasks, keys)  # (n, T)
    T = rewards.shape[1]
    q = T // 4
    q1, q4 = rewards[:, :q], rewards[:, -q:]
    # gate metric averaged over completed episodes in the final quarter
    m4, d4 = metrics[:, -q:], dones[:, -q:]
    gate_q4 = jnp.sum(m4 * d4) / jnp.maximum(jnp.sum(d4), 1.0)
    # per-lifetime slope sign test (Gate 1 locked statistic; one-sided
    # binomial, ties dropped)
    slopes = q4.mean(axis=1) - q1.mean(axis=1)
    n_pos = int((slopes > 0).sum())
    n_eff = int((slopes != 0).sum())
    return dict(
        reward_q1=float(q1.mean()),
        reward_q4=float(q4.mean()),
        slope=float(q4.mean() - q1.mean()),
        slope_pos_frac=n_pos / max(n_eff, 1),
        slope_sign_p=_binom_tail(n_pos, n_eff),
        gate_q4=float(gate_q4),
    )


def _binom_tail(k, n):
    """P(X >= k), X ~ Binomial(n, 0.5)."""
    from math import comb
    if n == 0:
        return 1.0
    return sum(comb(n, i) for i in range(k, n + 1)) / 2 ** n


def full_eval(env, params, n=100, seed=0):
    """Main condition plus PREREG controls."""
    return dict(
        main=eval_suite(env, params, n, seed),
        c4_coin_reward=eval_suite(env, params, n, seed, c4=True),
        c5_no_memory=eval_suite(env, params, n, seed, c5=True),
        c6_full_amnesia=eval_suite(env, params, n, seed, c6=True),
    )

# ===== changeling/train.py =====
"""Generation loop with jsonl logging and npz checkpoint/resume."""
import json
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np



def save_ckpt(path, theta, adam_state, key, gen, config):
    np.savez(
        path,
        theta=np.asarray(theta),
        adam_m=np.asarray(adam_state["m"]),
        adam_v=np.asarray(adam_state["v"]),
        adam_t=np.asarray(adam_state["t"]),
        key=np.asarray(key),
        gen=gen,
        config=json.dumps(config),
    )


def load_ckpt(path):
    z = np.load(path, allow_pickle=False)
    adam_state = dict(m=jnp.asarray(z["adam_m"]), v=jnp.asarray(z["adam_v"]),
                      t=jnp.int32(z["adam_t"]))
    return (jnp.asarray(z["theta"]), adam_state, jnp.asarray(z["key"]),
            int(z["gen"]), json.loads(str(z["config"])))


def train(config, resume=None):
    out = Path(config["out"])
    out.mkdir(parents=True, exist_ok=True)
    env = ENVS[config["env"]](**config.get("env_kwargs", {}))

    if resume:
        theta, adam_state, key, start_gen, saved_cfg = load_ckpt(resume)
        for k in ("env", "hidden", "pop", "sigma", "lr", "n_lifetimes"):
            assert saved_cfg[k] == config[k], f"resume config mismatch on {k}"
        _, unravel = flatten_params(
            init_gru(jax.random.PRNGKey(0), hidden=config["hidden"]))
        print(f"resumed gen={start_gen} from {resume}")
    else:
        key = jax.random.PRNGKey(config["seed"])
        key, ki = jax.random.split(key)
        params = init_gru(ki, hidden=config["hidden"])
        theta, unravel = flatten_params(params)
        adam_state = adam_init(theta.shape[0])
        start_gen = 0
        # C1 control: the random-init agent's eval, logged once up front
        c1 = full_eval(env, unravel(theta), n=config["eval_n"], seed=config["seed"])
        _log(out, dict(gen=-1, condition="c1_random_init", **_flat(c1)))

    from .rollout import FITNESS
    gen_step = make_gen_step(env, unravel, config["pop"],
                             config["n_lifetimes"], config["sigma"],
                             config["lr"],
                             fitness_fn=FITNESS[config.get("fitness", "late")])
    print(f"env={env['name']} dim={theta.shape[0]} pop={config['pop']} "
          f"M={config['n_lifetimes']} T={env['T']}")

    # survivability knobs (both optional, json-safe):
    #   max_seconds    — exit cleanly (checkpoint saved) before a session cap
    #   stop_gate      — stop once eval main.gate_q4 >= this
    #   stop_slope_pos — additionally require eval main.slope > 0 to stop
    max_seconds = config.get("max_seconds")
    stop_gate = config.get("stop_gate")
    stop_slope_pos = config.get("stop_slope_pos", False)

    t0 = time.time()
    for gen in range(start_gen, config["gens"]):
        if max_seconds is not None and time.time() - t0 > max_seconds:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen, config)
            print(f"wall-clock budget reached at gen {gen}; checkpointed, exiting")
            break
        key, kg = jax.random.split(key)
        theta, adam_state, stats = gen_step(theta, adam_state, kg)
        if (gen + 1) % config["log_every"] == 0:
            row = dict(gen=gen, sec=round(time.time() - t0, 1),
                       **{k: float(v) for k, v in stats.items()})
            _log(out, row)
            print(row)
        if (gen + 1) % config["eval_every"] == 0 or gen + 1 == config["gens"]:
            ev = full_eval(env, unravel(theta), n=config["eval_n"],
                           seed=config["seed"])
            _log(out, dict(gen=gen, **_flat(ev)))
            print(f"  eval g{gen}: main={ev['main']} "
                  f"c4={ev['c4_coin_reward']['gate_q4']:.3f} "
                  f"c5={ev['c5_no_memory']['gate_q4']:.3f}")
            if (stop_gate is not None and ev["main"]["gate_q4"] >= stop_gate
                    and (not stop_slope_pos or ev["main"]["slope"] > 0)):
                save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen + 1, config)
                print(f"stop criterion reached at gen {gen}; checkpointed, exiting")
                break
        if (gen + 1) % config["ckpt_every"] == 0 or gen + 1 == config["gens"]:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, gen + 1, config)

    return theta, unravel


def _flat(ev):
    return {f"{cond}.{k}": v for cond, d in ev.items() for k, v in d.items()}


def _log(out, row):
    with open(out / "log.jsonl", "a") as f:
        f.write(json.dumps(row) + "\n")

# ===== changeling/ppo.py =====
"""Route R2: PPO-RL^2 (Duan et al. 2016 protocol, clipped PPO objective).

Whole lifetimes are the trajectories; BPTT through the full lifetime; value
function does NOT reset at episode boundaries (the objective is lifetime
return). Training rewards carry the same late-weighting as R1 fitness
(PREREG_P0: selection pressure identical across routes); eval is untouched.

The deploy artifact is params["gru"] — the same pure S1 substrate as R1.
The value head exists only at training time (a connector, in SPEC terms).
"""
import json
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
from jax.flatten_util import ravel_pytree



def init_ppo_params(key, hidden=128):
    kg, kv = jax.random.split(key)
    return {
        "gru": init_gru(kg, hidden),
        "Wv": jax.random.normal(kv, (hidden, 1)) / jnp.sqrt(hidden),
        "bv": jnp.zeros(1),
    }


def collect(env, params, task, key, reward_scale):
    """One lifetime under the current policy. Returns everything the loss
    needs to recompute the forward pass exactly (teacher forcing on xs).
    Rewards come back late-weighted (PREREG_P0 selection pressure) and
    scaled so discounted returns are O(1) — otherwise the value-loss
    gradient through the shared trunk drowns the policy gradient."""
    T = env["T"]
    key, k0 = jax.random.split(key)
    state0, obs0 = env["reset"](k0, task)
    h0 = jnp.zeros(hidden_size(params["gru"]))
    carry0 = (h0, state0, obs0, jnp.zeros(N_ACT), jnp.float32(0.0),
              jnp.float32(1.0), key)

    def step_fn(carry, w_t):
        h, state, obs, last_a, last_r, boundary, key = carry
        key, ka, kr, kres = jax.random.split(key, 4)
        x = jnp.concatenate([obs, last_a, jnp.array([last_r, boundary])])
        h, logits = gru_step(params["gru"], h, x)
        logp_all = jax.nn.log_softmax(logits)
        a = jax.random.categorical(ka, logits)
        v = (h @ params["Wv"] + params["bv"])[0]
        state, obs, r, done, _ = env["step"](state, a, kr, task)
        rs_state, rs_obs = env["reset"](kres, task)
        state = jax.tree_util.tree_map(
            lambda new, old: jnp.where(done, new, old), rs_state, state)
        obs = jnp.where(done, rs_obs, obs)
        carry = (h, state, obs, jax.nn.one_hot(a, N_ACT), r,
                 done.astype(jnp.float32), key)
        out = (x, a, logp_all[a], v, r * w_t * reward_scale)
        return carry, out

    w = jnp.linspace(0.5, 1.5, T)
    _, (xs, acts, logps, vals, rews) = jax.lax.scan(step_fn, carry0, w)
    return xs, acts, logps, vals, rews


def gae(rews, vals, gamma, lam):
    """Advantages over the whole lifetime; terminal value 0 (lifetime over)."""
    vals_next = jnp.concatenate([vals[1:], jnp.zeros(1)])
    deltas = rews + gamma * vals_next - vals

    def back(carry, delta):
        carry = delta + gamma * lam * carry
        return carry, carry

    _, adv = jax.lax.scan(back, jnp.float32(0.0), deltas, reverse=True)
    return adv, adv + vals  # advantages, returns


def make_update_step(env, unravel, cfg):
    n_life = cfg["n_lifetimes"]
    gamma, lam = cfg["gamma"], cfg["lam"]
    clip, vf_c, ent_c = cfg["clip"], cfg["vf_coef"], cfg["ent_coef"]

    rew_scale = cfg.get("reward_scale", 1.0 - cfg["gamma"])

    def batch_collect(theta, key):
        params = unravel(theta)
        kt, kr = jax.random.split(key)
        tasks = jax.vmap(env["sample_task"])(jax.random.split(kt, n_life))
        keys = jax.random.split(kr, n_life)
        xs, acts, logps, vals, rews = jax.vmap(
            lambda t, k: collect(env, params, t, k, rew_scale))(tasks, keys)
        adv, rets = jax.vmap(lambda r, v: gae(r, v, gamma, lam))(rews, vals)
        adv = (adv - adv.mean()) / (adv.std() + 1e-8)
        return xs, acts, logps, adv, rets

    def loss_fn(theta, batch):
        params = unravel(theta)
        xs, acts, logps_old, adv, rets = batch
        h0 = jnp.zeros(hidden_size(params["gru"]))

        def forward(xs_one):
            def step(h, x):
                h, logits = gru_step(params["gru"], h, x)
                v = (h @ params["Wv"] + params["bv"])[0]
                return h, (logits, v)
            _, (logits, v) = jax.lax.scan(step, h0, xs_one)
            return logits, v

        logits, v = jax.vmap(forward)(xs)  # (B,T,K), (B,T)
        logp_all = jax.nn.log_softmax(logits)
        logp = jnp.take_along_axis(logp_all, acts[..., None], -1)[..., 0]
        ratio = jnp.exp(logp - logps_old)
        pg = jnp.minimum(ratio * adv,
                         jnp.clip(ratio, 1 - clip, 1 + clip) * adv).mean()
        vloss = 0.5 * ((v - rets) ** 2).mean()
        ent = -(jnp.exp(logp_all) * logp_all).sum(-1).mean()
        return -(pg - vf_c * vloss + ent_c * ent), dict(pg=pg, v=vloss, ent=ent)

    grad_fn = jax.value_and_grad(loss_fn, has_aux=True)

    def epoch_step(theta, adam_state, batch):
        (loss, aux), grad = grad_fn(theta, batch)
        gnorm = jnp.sqrt(jnp.sum(grad ** 2))
        grad = grad * jnp.minimum(1.0, cfg["max_grad_norm"] / (gnorm + 1e-8))
        theta, adam_state = adam_ascend(theta, -grad, adam_state, cfg["lr"])
        return theta, adam_state, loss, dict(aux, gnorm=gnorm)

    return jax.jit(batch_collect), jax.jit(epoch_step)


def train_ppo(config, resume=None):
    out = Path(config["out"])
    out.mkdir(parents=True, exist_ok=True)
    env = ENVS[config["env"]](**config.get("env_kwargs", {}))
    # eval (and therefore stop_gate) listens to the GATE task, which may
    # differ from the training distribution (e.g. mixture curricula)
    eval_env = ENVS[config["env"]](**config.get("eval_env_kwargs",
                                                config.get("env_kwargs", {})))

    if resume:
        theta, adam_state, key, start_up, saved_cfg = load_ckpt(resume)
        for k in ("env", "hidden", "n_lifetimes", "lr"):
            assert saved_cfg[k] == config[k], f"resume config mismatch on {k}"
        _, unravel = ravel_pytree(
            init_ppo_params(jax.random.PRNGKey(0), config["hidden"]))
        print(f"resumed update={start_up} from {resume}")
    else:
        key = jax.random.PRNGKey(config["seed"])
        key, ki = jax.random.split(key)
        theta, unravel = ravel_pytree(init_ppo_params(ki, config["hidden"]))
        adam_state = adam_init(theta.shape[0])
        start_up = 0

    batch_collect, epoch_step = make_update_step(env, unravel, config)
    print(f"R2 PPO env={env['name']} dim={theta.shape[0]} "
          f"B={config['n_lifetimes']} T={env['T']}")

    max_seconds = config.get("max_seconds")
    stop_gate = config.get("stop_gate")
    stop_slope_pos = config.get("stop_slope_pos", False)

    t0 = time.time()
    for up in range(start_up, config["updates"]):
        if max_seconds is not None and time.time() - t0 > max_seconds:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, up, config)
            print(f"wall-clock budget reached at update {up}; exiting")
            break
        key, kc = jax.random.split(key)
        batch = batch_collect(theta, kc)
        for _ in range(config["epochs"]):
            theta, adam_state, loss, aux = epoch_step(theta, adam_state, batch)
        if (up + 1) % config["log_every"] == 0:
            row = dict(update=up, sec=round(time.time() - t0, 1),
                       loss=float(loss), pg=float(aux["pg"]),
                       vloss=float(aux["v"]), ent=float(aux["ent"]),
                       gnorm=float(aux["gnorm"]))
            _log(out, row)
            print(row)
        if (up + 1) % config["eval_every"] == 0 or up + 1 == config["updates"]:
            ev = full_eval(eval_env, unravel(theta)["gru"], n=config["eval_n"],
                           seed=config["seed"])
            _log(out, dict(update=up, **_flat(ev)))
            print(f"  eval u{up}: main={ev['main']} "
                  f"c4={ev['c4_coin_reward']['gate_q4']:.3f} "
                  f"c5={ev['c5_no_memory']['gate_q4']:.3f}")
            if (stop_gate is not None and ev["main"]["gate_q4"] >= stop_gate
                    and (not stop_slope_pos or ev["main"]["slope"] > 0)):
                save_ckpt(out / "ckpt.npz", theta, adam_state, key, up + 1, config)
                print(f"stop criterion reached at update {up}; exiting")
                break
        if (up + 1) % config["ckpt_every"] == 0 or up + 1 == config["updates"]:
            save_ckpt(out / "ckpt.npz", theta, adam_state, key, up + 1, config)

    return theta, unravel


# ===== kernel main (route: ppo) =====
if __name__ == "__main__":
    import glob
    import os

    ROUTE = "ppo"
    GATE_BANDIT = 0.672  # 0.90 x Thompson reference 0.747 (PREREG deviation D1)
    smoke = os.environ.get("CHANGELING_SMOKE") == "1"
    print("jax devices:", jax.devices())
    base = "/kaggle/working" if os.path.isdir("/kaggle/working") else "runs_kernel"
    wall_start = time.time()
    WALL_BUDGET = 7.5 * 3600  # exit cleanly well inside Kaggle's session cap

    def find_resume(name):
        """Resume from a prior session's checkpoint, attached as a DATASET
        (kernel_sources mounts code, not outputs — probed 2026-06-12)."""
        hits = sorted(h for h in
                      glob.glob("/kaggle/input/**/ckpt.npz", recursive=True)
                      if name in h)
        return hits[0] if hits else None

    if ROUTE == "es":
        common = dict(hidden=128, pop=256, n_lifetimes=8, sigma=0.03, lr=0.02,
                      seed=0, eval_n=100, eval_every=200, log_every=25,
                      ckpt_every=100)
        jobs = [("bandit", dict(gens=3000, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True)),
                ("catch", dict(gens=3000, stop_gate=0.90))]
        trainer = train
    else:
        common = dict(hidden=128, n_lifetimes=64, lr=5e-4, gamma=0.99,
                      lam=0.95, clip=0.2, epochs=4, vf_coef=0.5,
                      ent_coef=0.01, max_grad_norm=0.5, seed=0,
                      eval_n=100, eval_every=250, log_every=50,
                      ckpt_every=250)
        jobs = [("bandit", dict(updates=24000, stop_gate=GATE_BANDIT,
                                stop_slope_pos=True,
                                env_kwargs=dict(mix=0.5),
                                eval_env_kwargs=dict()))]  # stop listens to gate task
        trainer = train_ppo
    if smoke:
        common.update(hidden=32, eval_n=20, eval_every=5, log_every=1,
                      ckpt_every=5)
        gens_key = "gens" if ROUTE == "es" else "updates"
        jobs = [(n, dict(d, **{gens_key: 5})) for n, d in jobs]

    for name, extra in jobs:
        cfg = dict(env=name, out=f"{base}/gate_{name}_ppo",
                   max_seconds=WALL_BUDGET - (time.time() - wall_start),
                   **common, **extra)
        resume = find_resume(f"gate_{name}_ppo")
        print(f"\n##### {name} [ppo]: resume={resume}")
        theta, unravel = trainer(cfg, resume=resume)
        params = unravel(theta) if ROUTE == "es" else unravel(theta)["gru"]
        ev = full_eval(ENVS[name](), params, n=cfg["eval_n"], seed=cfg["seed"])
        m, c4, c5 = ev["main"], ev["c4_coin_reward"], ev["c5_no_memory"]
        print(f"\n=== GATE 0 verdict: {name} [ppo] ===")
        if name == "bandit":
            print(f"G0-A gate_q4={m['gate_q4']:.3f} (>={GATE_BANDIT}, D1):",
                  "PASS" if m["gate_q4"] >= GATE_BANDIT else "FAIL")
            print(f"G0-A slope={m['slope']:+.4f} (>0):",
                  "PASS" if m["slope"] > 0 else "FAIL")
            print(f"G0-B c4={c4['gate_q4']:.3f} (<=0.225):",
                  "PASS" if c4["gate_q4"] <= 0.225 else "FAIL")
            print(f"G0-C c5={c5['gate_q4']:.3f} (<=0.225):",
                  "PASS" if c5["gate_q4"] <= 0.225 else "FAIL")
        else:
            print(f"G0-D gate_q4={m['gate_q4']:.3f} (>=0.90):",
                  "PASS" if m["gate_q4"] >= 0.90 else "FAIL")
    print("\ntotal wall:", round(time.time() - wall_start), "s")
